# Generated by Django 3.2 on 2021-05-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210515_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(default=users.models.Order.generateUUID, editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('В процессе', 'В процессе'), ('Принят', 'Принят'), ('Оформлен', 'Оформлен'), ('Отменен', 'Отменен')], default='Оформлен', max_length=100, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Стоимость')),
                ('commentary', models.TextField(blank=True, max_length=500, verbose_name='Комментарий к заказу')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказы')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
    ]
