# Generated by Django 3.2 on 2021-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Отменен', 'Отменен'), ('Принят', 'Принят'), ('Оформлен', 'Оформлен')], default='Оформлен', max_length=100, verbose_name='Статус'),
        ),
    ]
