# Generated by Django 3.2 on 2021-05-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_feedback_options'),
        ('users', '0006_auto_20210517_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Принят', 'Принят'), ('Оформлен', 'Оформлен'), ('Отменен', 'Отменен')], default='Оформлен', max_length=100, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='mainpage.services', verbose_name='Услуга')),
            ],
        ),
    ]
