# Generated by Django 3.2 on 2021-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210518_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Отменен', 'Отменен'), ('Оформлен', 'Оформлен'), ('Принят', 'Принят')], default='Оформлен', max_length=100, verbose_name='Статус'),
        ),
    ]
