# Generated by Django 3.2 on 2021-05-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Оформлен', 'Оформлен'), ('Принят', 'Принят'), ('Отменен', 'Отменен')], default='Оформлен', max_length=100, verbose_name='Статус'),
        ),
    ]
