# Generated by Django 3.2 on 2021-05-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Отменен', 'Отменен'), ('Оформлен', 'Оформлен'), ('В процессе', 'В процессе'), ('Принят', 'Принят')], default='Оформлен', max_length=100, verbose_name='Статус'),
        ),
    ]
