# Generated by Django 3.2 on 2021-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Оформлен', 'Оформлен'), ('В процессе', 'В процессе'), ('Отменен', 'Отменен')], default='Оформлен', max_length=100, verbose_name='Статус'),
        ),
    ]
