# Generated by Django 3.2 on 2021-06-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.orderitem', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Оформлен', 'Оформлен'), ('Отменен', 'Отменен'), ('Принят', 'Принят')], default='Оформлен', max_length=100, verbose_name='Статус'),
        ),
    ]
