# Generated by Django 3.2 on 2021-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210603_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оформлен', 'Оформлен'), ('В процессе', 'В процессе'), ('Принят', 'Принят'), ('Отменен', 'Отменен')], default='Оформлен', max_length=100, verbose_name='Статус'),
        ),
    ]
