# Generated by Django 3.2 on 2021-05-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
