# Generated by Django 3.2 on 2021-05-10 08:10

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
