# Generated by Django 3.2 on 2021-05-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
