# Generated by Django 3.2 on 2021-05-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
    ]
