# Generated by Django 3.2 on 2021-05-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Стоимость'),
        ),
    ]
