# Generated by Django 3.2 on 2021-06-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like',
        ),
    ]
