# Generated by Django 3.2 on 2021-06-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_rename_likes_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
